# Delay (in Seconds) before a regeneration starts.
# (The time between the explosion and regeneration)

delay: 10

# Frequency of regeneration (in server ticks).
# (How fast the regeneration runs)

frequency: 5

# List of materials to skip during block regeneration
skipMaterials:
  - 'FIRE'
  - 'TNT'