name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
api-version: ${project.bukkitAPIVersion}

author: TamShep
website: https://vshepherd.com

description: >
    ${project.description}

softdepend: []

